apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # use a StorageClass válida do seu cluster. Em minikube é geralmente "standard".
  # Se preferir usar a default, remova a linha abaixo.
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: teixeiradev/projeto-database:1.0
          imagePullPolicy: Always
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Senha12;"
            - name: MYSQL_DATABASE
              value: "meubanco"
          volumeMounts:
            - name: mysql-dados
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: teixeiradev/projeto-php:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: php
